---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2.0

inputs:
  - name: git-resource

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))
  NAME: ap-south-1a
  REGION: ap-south-1

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      export NAME=$NAME
      export REGION=$REGION
      export VAULT_ADDR=$VAULT_ADDR
      export VAULT_TOKEN=$SSH_TOKEN
      vault login --no-print $VAULT_TOKEN
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION
      aws sts get-caller-identity --query Account --output text
      chmod a+x git-resource/tasks/aws_deploy/mumbai/aws_env_deploy.sh
      ./git-resource/tasks/aws_deploy/mumbai/aws_env_deploy.sh


      