---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2.0

inputs:
  - name: git-resource

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  NAME: us-west-1a
  REGION: us-west-1
  UBUNTU_AMI_ID: ami-027fe87f84c9595c7
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      export NAME=$NAME
      export AZ=$NAME
      export UBUNTU_AMI_ID=$UBUNTU_AMI_ID
      export VAULT_ADDR=$VAULT_ADDR
      export VAULT_TOKEN=$SSH_TOKEN
      vault login --no-print $VAULT_TOKEN
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION
      aws sts get-caller-identity --query Account --output text
      export router_sg_id=$(vault kv get --field=router_sg_id concourse/cisco-fso-labs/$NAME/router_sg_id)
      chmod a+x git-resource/tasks/appd/aws_deploy_supercar.sh
      ./git-resource/tasks/appd/aws_deploy_supercar.sh

      