---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2.0

inputs:
  - name: git-resource

params:
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))
  NAME: us-west-1a

run:
  path: /bin/sh
  args:
    - -ce
    - |
      cd git
      python3 -m pip install --upgrade pip
      pip3 install netmiko
      apt -y install ncurses-term
      chmod a+x configure_te_agent.sh
      ./configure_te_agent.sh







