display:
  background_image: https://tetacourse.com/uploads/posts/2020-07/1595211523_1.jpg
jobs:
  - name: lab-prep
    plan:
      - get: git-resource
        trigger: true
      - config:
          image_resource:
            name: ""
            source:
              repository: sconrod/python-aws-image
              tag: 2
            type: docker-image
          inputs:
            - name: git-resource
          platform: linux
          run:
            path: sh
            args:
              - -ce
              - |
                export AWS_PAGER=""
                export Name=$NAME
                echo $NAME
                aws configure set aws_access_key_id $AWS_KEY_ID
                aws configure set aws_secret_access_key $AWS_KEY
                aws configure set default.region $REGION
                aws sts get-caller-identity --query Account --output text
                echo "WELCOME TO THE CISCO FSO API LAB FOR DEVOPS/NETOPS ENGINEERS"

        task: check-aws
        params:
          AWS_KEY_ID: ((Access_key_ID.Access_key))
          AWS_KEY: ((Secret_access_key.Secret_access_key))
          REGION: ((aws.region))
          NAME: ((az.name))
          VAULT_ADDR: ((vault.addr))

  - name: ap-south-1-Mumbai
    public: true
    plan:
      - get: git-resource
        passed: [lab-prep]
      - task: aws_deploy_key
        file: git-resource/tasks/aws_deploy/mumbai/aws_key_deploy.yml
      - task: aws_deploy_vpc
        file: git-resource/tasks/aws_deploy/mumbai/aws_env_deploy.yml
      - task: aws_deploy_ubuntu_mumbai
        file: git-resource/tasks/aws_deploy/mumbai/aws_deploy_ubuntu.yml

resource_types:
resources:
  - name: git-resource
    source:
      Username: ((Username))
      branch: main
      email: ((email))
      private_key: ((private_key))
      uri: ((git-uri))
    type: git
