---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2.0

inputs:
  - name: git-resource

params:
  AWS_KEY_ID: ((Access_key_ID.Access_key))
  AWS_KEY: ((Secret_access_key.Secret_access_key))
  NAME: us-west-1a
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      export NAME
      echo $NAME
      export VAULT_ADDR=$VAULT_ADDR
      export VAULT_TOKEN=$SSH_TOKEN
      vault login --no-print $VAULT_TOKEN
      export REGION=$(vault kv get --field=region concourse/cisco-fso-labs/$NAME/region)
      export AZ=$(vault kv get --field=az concourse/cisco-fso-labs/$NAME/az)
      echo $REGION
      echo $AZ
      aws configure set aws_access_key_id $AWS_KEY_ID
      aws configure set aws_secret_access_key $AWS_KEY
      aws configure set default.region $REGION
      aws sts get-caller-identity --query Account --output text
      export REGION=$(vault kv get --field=region concourse/cisco-fso-labs/$NAME/region)
      export AZ=$(vault kv get --field=az concourse/cisco-fso-labs/$NAME/az)
      export router_sg_id=$(vault kv get --field=router_sg_id concourse/cisco-fso-labs/$NAME/router_sg_id)
      chmod a+x git-resource/tasks/aws_deploy/aws_deploy_ubuntu.sh
      ./git-resource/tasks/aws_deploy/aws_deploy_ubuntu.sh

      