---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/python-aws-image
    tag: 2
inputs:
  - name: git-resource
params:
  VAULT_ADDR: http://dev-vault.ciscolivedemo2022.com:8200
  SSH_TOKEN: hvs.CAESIJKFONlcSc8S4fo6-EwBsQwf2JxxrQPUGN8pPCh9_W77Gh4KHGh2cy43YzRVcTkzT1p2VWdRdVFJb1BkNnJCbHY
run:
  path: /bin/sh
  args:
    - -ce
    - |
      chmod a+x git-resource/tasks/aws_deploy/vault_prep.sh
      ./git-resource/tasks/aws_deploy/vault_prep.sh