---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sconrod/thousandeyes-image
    tag: 1

inputs:
  - name: git-resource

params:
  VAULT_ADDR: http://dev-vault.devops-ontap.com:8200
  SSH_TOKEN: ((ssh-token.token))

run:
  path: /bin/sh
  args:
    - -ce
    - |
      export AWS_PAGER=""
      NAME='us-west-1a'
      export NAME
      echo $NAME
      chmod a+x git-resource/tasks/te/te_agents_install.sh
      ./git-resource/tasks/te/te_agents_install.sh


      